# db configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog-app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
        #create, update, create-drop, validate

   # image configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # username, password, role config
#  security:
#    user:
#      name: deepak
#      password: deepak
#      roles:
#        - ADMIN

#  mail configurations
  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: your_gmail_id
#    password: your_gmail_password
#   to use local mail server, you need to download maildev
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  output:
    ansi:
      enabled: ALWAYS

   # image path
project:
  image: images/

logging:
  level:
    org:
      springframework:
        security: DEBUG